### ISSUE TITLE
JSON format generated for Manifest is not correct

### ISSUE THREAD

**Issue by ctnaveenkumar** [wrobstory/redifest#2]
Hi 

The JSON format generated for manifest is in correct. It should have double quotes instead of single quotes. Also character u is appended with 's3

Incorrect JSON:

{'entries': [{'mandatory': True,
              'url': u's3://mybucket/folder1/folder2/foo.json'},
             {'mandatory': True,
              'url': u's3://mybucket/folder1/folder2/bar.json'},
             {'mandatory': True,
               'url': u's3://mybucket/folder3/bar.json'}]}

Correct JSON:

{
    "entries": [
        {
            "mandatory": "True",
            "url": "s3://mybucket/folder1/folder2/foo.json"
        },
        {
            "mandatory": "True",
            "url": "s3://mybucket/folder1/folder2/bar.json"
        },
        {
            "mandatory": "True",
            "url": "s3://mybucket/folder3/bar.json"
        }
    ]
}

**Comment by wrobstory** [comment]
The example in the documentation is a Python representation of the manifest, where single quotes are valid string identifiers and the prepended `u` means that we're dealing with unicode. When serialized to JSON it will be formatted correctly.
